FROM python:3.9.9-bullseye

RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y nodejs

WORKDIR /src

RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
RUN apt-get install git-lfs -y
RUN git clone https://huggingface.co/TheBloke/airoboros-7B-gpt4-1.2-GGML
RUN mv airoboros-7B-gpt4-1.2-GGML/airoboros-7b-gpt4-1.2.ggmlv3.q3_K_M.bin ./models/
RUN rm -rf airoboros-7B-gpt4-1.2-GGML/

COPY requirements.txt ./
RUN pip3 install -r requirements.txt

COPY models ./models/
COPY images ./images/
COPY scripts ./scripts/
COPY bot_memories ./bot_memories/
COPY bot_personalities ./bot_personalities/
COPY .env ./


ENV HOST=0.0.0.0

ENTRYPOINT ["python3", "scripts/main.py"]
